server:
  port: 8012

spring:
  application:
    name: file-server
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC
    username: test
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 512MB
      max-request-size: 512MB

file-server:
  repertory: C:\Users\zhaoj\AppData\Local\Temp
  temp: C:\Users\zhaoj\documents

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8000/eureka/
